---

title: Diversitechy
name: Diversitechy
description: Diversitechy community website.

paginate: 10

timezone: UTC

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
